### ISSUE TITLE
Add OIDC login option for ABS

### ISSUE THREAD

**Issue by 11qu1d** [prologueapp/Prologue#70] opened 2024-10-13 21:08 UTC
For users on ABS servers utilising OIDC for authentication, it not currently possible to login via Prologue as there is no such option.

Would be great to include that feature in order to get more people testing the beta on TestFlight.

Thanks

**Comment by vicegold** [comment] 2024-10-13 21:10
#39

**Comment by lcharlick** [comment] 2024-12-15 06:54
Duplicate of #39

**Closed as completed by lcharlick** 2024-12-15 06:54 UTC
